### ISSUE TITLE
Where is the release drafter template (.github/release-drafter.yml)

### ISSUE THREAD

**Issue by brenner-tobias** [hassio-addons/addon-example#110]
# Problem/Motivation

> I built my add-on following this structure which is awesome. For the release-drafter though, I created my own very simple template. I am wondering where the template of this and other add-ons in this organisation are located, since I cannot find it in any add-on and also not in the workflow repository.

## Expected behavior

> Would have expected a release-drafter.yml in .github int eh repository or at least in the workflow repository

## Actual behavior

> Cannot find any in the whole organisation

**Comment by frenck** [comment]
The `.github` meta repo: <https://github.com/hassio-addons/.github/blob/main/.github/release-drafter.yml>
