### ISSUE TITLE
nothing happened

### ISSUE THREAD

**Issue by zinker** [hassio-addons/addon-example#15]
see only this in logs after starting

[20:43:13] INFO: Starting Example1...
./run: line 10: /usr/bin/example1.sh: Permission denied
[20:43:14] INFO: Starting Example2...
./run: line 10: /usr/bin/example2.sh: Permission denied
[20:43:14] INFO: Starting Example1...
./run: line 10: /usr/bin/example1.sh: Permission denied
[20:43:15] INFO: Starting Example2...
./run: line 10: /usr/bin/example2.sh: Permission denied
[20:43:15] INFO: Starting Example1...
./run: line 10: /usr/bin/example1.sh: Permission denied

**Comment by djmalin** [comment]
I have the same problem

Add-on version: 3.1.0
 You are running the latest version of this add-on.
 System: HassOS 3.6  (armv7 / raspberrypi3)
 Home Assistant version: 0.103.0
 Supervisor version: 193
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[14:23:08] INFO: Starting Example2...
[14:23:08] INFO: Starting Example1...
./run: line 10: ./run: line 10: /usr/bin/example1.sh: Permission denied/usr/bin/example2.sh: Permission denied
[14:23:09] INFO: Starting Example2...
[14:23:09] INFO: Starting Example1...

**Comment by sinclairpaul** [comment]
Look at the referenced PR if you want a fix.
