### ISSUE TITLE
missing chmod on entry scripts?

### ISSUE THREAD

**Issue by akshaya-a** [hassio-addons/addon-example#156]
# Problem/Motivation

permission denied executing service scripts following addon template

(in case it matters I'm ussing the addon debian-base, not alpine

## Expected behavior

it runs

## Actual behavior

./run: line 6: /usr/bin/run_gateway.sh: Permission denied

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

There was previous discussion on this, but with #126 I didn't see the chmod commands carry over. Adding explicit RUN chmod a+x on my scripts successfully worked past this issue

**Comment by sinclairpaul** [comment]
Are you following the example at <https://github.com/hassio-addons/addon-example/blob/3c2f73492d012ec52d4139a0e34c1839af223a20/example/rootfs/etc/s6-overlay/s6-rc.d/example1/run#L1-L10>

**Comment by frenck** [comment]
> I didn't see the chmod commands carry over

Those aren't carried over. You have to apply the right permissions and commit those.

Closing this issue, as the permissions in this repository are correct and the add-on is in a working state.

../Frenck
