### ISSUE TITLE
No permission for example add-on

### ISSUE THREAD

**Issue by Ergerbolt** [hassio-addons/addon-example#17]
# Problem/Motivation

Log tells me: 

`[17:35:42] INFO: Starting Example1...
./run: line 10: /usr/bin/example1.sh: Permission denied
[17:35:42] INFO: Starting Example2...
./run: line 10: /usr/bin/example2.sh: Permission denied`

I tried to restart, but there was no success for me. 
Im using Hass.io 0.103 with a Rasperry Pi 3+.

Maybe someone can help?

**Comment by sinclairpaul** [comment]
See #15
