### ISSUE TITLE
Logging fails in example

### ISSUE THREAD

**Issue by MarcJenningsUK** [hassio-addons/addon-example#18]
# Problem/Motivation

> Trying to learn, but the example is broken

## Expected behavior

> Log shows quotes

## Actual behavior

> from plugin log 
> [12:14:00] INFO: Starting Example2...
> ./run: line 10: /usr/bin/example2.sh: Permission denied
> [12:14:00] INFO: Starting Example1...
> ./run: line 10: /usr/bin/example1.sh: Permission denied
> [12:14:01] INFO: Starting Example2...
> ./run: line 10: /usr/bin/example2.sh: Permission denied
> [12:14:01] INFO: Starting Example1...
> ./run: line 10: /usr/bin/example1.sh: Permission denied
> [12:14:02] INFO: Starting Example2...
> ./run: line 10: /usr/bin/example2.sh: Permission denied

## Steps to reproduce

> install plugin

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
#15 #17
