### ISSUE TITLE
docker install fails after adding to my own repository

### ISSUE THREAD

**Issue by alpharesearch** [hassio-addons/addon-example#36]
# Problem/Motivation

I can install the example addon from the default repository via Android without issues (but for some reason, I don't see it on the PC web page?). But when I copy just the example folder to my own repository I get an error when I try to install. I also get the same error on one other repository that also uses some of the example as a base. https://github.com/sdesalve/hassio-addons/issues/32

## Expected behavior

installed the addon from my own repository just like from the default repository

## Actual behavior

The command '/bin/ash -o pipefail -c apk add --no-cache coreutils=8.32-r2 wget=1.21.1-r1' returned a non-zero code: 2

## Steps to reproduce

I'm using Linux Mint 19 and I did clone my and the example repository to my local drive. Next, I copied just the example folder from this cloned repository to my cloned repository. Last I push everything for my repository back to Github. In the addon store I do a reload and then I select install from my repository. I get the error and some more red text in the log.

## System

System: Raspbian GNU/Linux 10 (buster)  (armv7 / raspberrypi4)
Docker version 20.10.1
Home Assistant Core: 2021.1.4
Home Assistant Supervisor: 2021.01.5
Btw, I was able to install other updates to day like node red and the time server addon without issues.

**Comment by frenck** [comment]
>  '/bin/ash -o pipefail -c apk add --no-cache coreutils=8.32-r2 wget=1.21.1-r1'

That log is incomplete. please share full logs.

**Comment by alpharesearch** [comment]
21-01-22 18:32:49 INFO (SyncWorker_5) [supervisor.docker.addon] Starting build for ed48e72c/armv7-addon-example:dev
21-01-22 18:32:52 ERROR (SyncWorker_5) [supervisor.docker.addon] Can't build ed48e72c/armv7-addon-example:dev: The command '/bin/ash -o pipefail -c apk add --no-cache     coreutils=8.32-r2     wget=1.21.1-r1' returned a non-zero code: 2
21-01-22 18:32:52 ERROR (SyncWorker_5) [supervisor.docker.addon] Build log: 
Step 1/18 : ARG BUILD_FROM=ghcr.io/hassio-addons/base/amd64:9.0.1


Step 2/18 : FROM ${BUILD_FROM}


 ---> 8b4f1febe3a8

Step 3/18 : COPY rootfs /


 ---> Using cache

 ---> d5dd23b938d4

Step 4/18 : RUN apk add --no-cache     coreutils=8.32-r2     wget=1.21.1-r1


 ---> Running in 02f4a0c1203b

fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz

WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: temporary error (try again later)

fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz

WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: temporary error (try again later)
ERROR: unable to select packages:

  coreutils (no such package):
    required by: world[coreutils=8.32-r2]
  wget (no such package):
    required by: world[wget=1.21.1-r1]

Removing intermediate container 02f4a0c1203b

**Comment by frenck** [comment]
`WARNING: Ignoring dl-cdn.alpinelinux.org/alpine/v3.13/main: temporary error (try again later)`

That is an external issue not related to the add-on. Make sure you have internet access, otherwise the issue might be the Alpine content delivery network.

Either way, I cannot resolve a "try again later" response from an external resource

**Comment by alpharesearch** [comment]
Now I installed your version:
21-01-22 18:34:17 INFO (MainThread) [supervisor.addons] Creating Home Assistant add-on data folder /data/addons/data/a0d7b954_example
21-01-22 18:34:17 INFO (SyncWorker_3) [supervisor.docker.interface] Downloading docker image ghcr.io/hassio-addons/example/armv7 with tag 4.0.4.
21-01-22 18:34:19 INFO (MainThread) [supervisor.addons] Add-on 'a0d7b954_example' successfully installed

**Comment by frenck** [comment]
That is a pre-build docker image, it doesn't rely on the resource that is reported in a temporary error.

**Comment by alpharesearch** [comment]
Okay, thank you.

**Comment by alpharesearch** [comment]
I think I found the issue, when the container gets created it connects to the default network bridge, when the container normally starts it gets connected to hassio network bridge. 
Is there any way to have it also connect to the hassio network bridge when it gets created?
For example, I can take the run command out of the dockerfile on the example and it creates the addon. Now I can attach a bash as root to the container and install all the packages with the command from RUN.
But I guess I should also be able to configure the default network bridge to be able to access the internet.

**Comment by alpharesearch** [comment]
Looks like this new behavior may also affect the officially supported Debian versions. So just as a reference here is what I did as a workaround. I created the default.json file in the /etc/docker/ directory as outline here: https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0#time64_requirements  and next, I added the seccomp-profile option to /etc/docker/daemon.json file to use it. Here is the content of my file now:
{
    "seccomp-profile": "/etc/docker/default.json",
    "log-driver": "journald",
    "storage-driver": "overlay2"
}

**Comment by y0ast** [comment]
I have the same problem, but your suggested seccomp-profile didn't fix it. 

Did you place https://github.com/moby/moby/blob/master/profiles/seccomp/default.json in `/etc/docker/default.json`?

Moving back to an alpine 3.12 based image does fix it! (or workaround it more accurately...)

**Comment by alpharesearch** [comment]
> Did you place https://github.com/moby/moby/blob/master/profiles/seccomp/default.json in `/etc/docker/default.json`?

Yes, but I believe it's not important. I think as long as you reference the downloaded file in the  /etc/docker/daemon.json you should be good.

**Comment by sinclairpaul** [comment]
> Looks like this new behavior may also affect the officially supported Debian versions

Just to clarify on this discussion, the issue on Debian can be rectified by adding the backports repo (and these are some of the challenges in running a Supervised installation).

Other instructions can be found on the Alpine site itself.

**Comment by y0ast** [comment]
@alpharesearch Ah, I missed the editing step on the wiki.

Line 2 of default.json is:
```
	"defaultAction": "SCMP_ACT_ERRNO",
```
And needs to be edited to:
```
	"defaultAction": "SCMP_ACT_TRACE",
```

Then it indeed works fine again :)

When searching around on this issue there's surprisingly little information! I would've expected lots of people to build docker containers with alpine 3.13 on raspbian (or raspberrypi os), also outside of the HA community!
